import { ROUTE_NAMES, ROUTE_PATHS } from './app.constants'

export const APP_ROUTES = {
  HOME: { NAME: ROUTE_NAMES.HOME, PATH: ROUTE_PATHS.HOME },
  AUTH: {
    LOGIN: { NAME: ROUTE_NAMES.LOGIN, PATH: ROUTE_PATHS.LOGIN },
    REGISTER: { NAME: ROUTE_NAMES.REGISTER, PATH: ROUTE_PATHS.REGISTER },
  },
  DASHBOARD: {
    HOME: { NAME: ROUTE_NAMES.DASHBOARD, PATH: ROUTE_PATHS.DASHBOARD },
  },
  USERS: {
    LIST: { NAME: ROUTE_NAMES.USERS, PATH: ROUTE_PATHS.USERS },
  },
  NOT_FOUND: { NAME: ROUTE_NAMES.NOT_FOUND, PATH: ROUTE_PATHS.NOT_FOUND },
} as const
