export const HTTP_HEADER = {
    INTERNAL_API_KEY: 'Internal-Api-Key',
    API_KEY: 'Api-Key',

    TENANT_ID: 'Tenant-Id',

    REQUEST_ID: 'Request-Id',
    CORRELATION_ID: 'Correlation-Id',

    CLIENT_TYPE: 'Client-Type',
    CLIENT_ID: 'Client-Id',

    RATE_LIMIT_REMAINING: 'RateLimit-Remaining',
    RATE_LIMIT_RESET: 'RateLimit-Reset',

    CONTENT_SECURITY_POLICY: 'Content-Security-Policy',
    FRAME_OPTIONS: 'Frame-Options',
    CONTENT_TYPE_OPTIONS: 'Content-Type-Options',
    XSS_PROTECTION: 'XSS-Protection',
    STRICT_TRANSPORT_SECURITY: 'Strict-Transport-Security',

    AUTHORIZATION: 'Authorization',
    CONTENT_TYPE: 'Content-Type',
    ACCEPT: 'Accept',

    ACCEPT_LANGUAGE: 'Accept-Language',
    ACCEPT_ENCODING: 'Accept-Encoding',
    USER_AGENT: 'User-Agent',

    TIMEZONE: 'Timezone',

    TRACEPARENT: 'traceparent',
} as const

export const HTTP_STATUS = {
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    TOO_MANY: 429,
    SERVER_ERROR: 500,
} as const

export type HttpHeaderKey = (typeof HTTP_HEADER)[keyof typeof HTTP_HEADER]

export const ERROR_CODES = {
    // GENERAL
    NONE: 'NONE',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_SUPPORTED: 'NOT_SUPPORTED',
    OPERATION_CANCELLED: 'OPERATION_CANCELLED',
    OPERATION_TIMEOUT: 'OPERATION_TIMEOUT',
    BAD_REQUEST: 'BAD_REQUEST',
    CONCURRENCY_CONFLICT: 'CONCURRENCY_CONFLICT',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    INVALID_ARGUMENT: 'INVALID_ARGUMENT',
    INVALID_OPERATION: 'INVALID_OPERATION',

    // VALIDATION
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
    FIELD_OUT_OF_RANGE: 'FIELD_OUT_OF_RANGE',
    INVALID_FORMAT: 'INVALID_FORMAT',
    DUPLICATE_VALUE: 'DUPLICATE_VALUE',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
    INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
    PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
    INVALID_REFERENCE: 'INVALID_REFERENCE',

    // AUTH
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
    ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
    ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
    TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
    TWO_FACTOR_CODE_INVALID: 'TWO_FACTOR_CODE_INVALID',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    API_KEY_INVALID: 'API_KEY_INVALID',
    API_KEY_REVOKED: 'API_KEY_REVOKED',

    // RESOURCE
    NOT_FOUND: 'NOT_FOUND',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    RESOURCE_LOCKED: 'RESOURCE_LOCKED',
    INVALID_STATE: 'INVALID_STATE',
    RESOURCE_DELETED: 'RESOURCE_DELETED',
    RESOURCE_VERSION_MISMATCH: 'RESOURCE_VERSION_MISMATCH',
    RESOURCE_LIMIT_REACHED: 'RESOURCE_LIMIT_REACHED',

    // BUSINESS
    BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
    INVALID_WORKFLOW_TRANSITION: 'INVALID_WORKFLOW_TRANSITION',
    DEPENDENCY_CONSTRAINT_VIOLATION: 'DEPENDENCY_CONSTRAINT_VIOLATION',
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
    QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
    APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',

    // USER
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
    USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
    PASSWORD_SAME_AS_OLD: 'PASSWORD_SAME_AS_OLD',
    CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
    PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',
    PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
    PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',

    // PAYMENT
    PAYMENT_DECLINED: 'PAYMENT_DECLINED',
    INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    FRAUD_DETECTED: 'FRAUD_DETECTED',
    REFUND_ALREADY_PROCESSED: 'REFUND_ALREADY_PROCESSED',
    REFUND_AMOUNT_EXCEEDED: 'REFUND_AMOUNT_EXCEEDED',
    INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
    SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
    SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
    UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',

    //FILE
    FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
    FILE_SIZE_TOO_LARGE: 'FILE_SIZE_TOO_LARGE',
    FILE_CORRUPTED: 'FILE_CORRUPTED',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
    STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
    FILE_GENERATION_FAILED: 'FILE_GENERATION_FAILED',

    //   INFRASTRUCTURE
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
    EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
    EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
    DATABASE_ERROR: 'DATABASE_ERROR',
    DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    NETWORK_ERROR: 'NETWORK_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
