export { default as HomeNav } from './components/HomeNav.vue'
export { default as HomeHero } from './components/HomeHero.vue'
export { default as HomeAbout } from './components/HomeAbout.vue'
export { default as HomeMenu } from './components/HomeMenu.vue'
export { default as HomeFranchise } from './components/HomeFranchise.vue'
export { default as HomeFaq } from './components/HomeFaq.vue'
export { default as HomeContact } from './components/HomeContact.vue'
export { default as HomeFooter } from './components/HomeFooter.vue'
export * from './types/home.types'
export * from './data/home.constants'
